package com.monac.parser;

public enum NodeType {

    TRANSLATION_UNIT,
    EXTERNAL_DECLARATION,
    FUNCTION_DEFINITION,
    DECLARATION_SPECIFIER,
    STORAGE_CLASS_SPECIFIER,
    TYPE_SPECIFIER,
    STRUCT_OR_UNION_SPECIFIER,
    STRUCT_OR_UNION,
    STRUCT_DECLARATION,
    SPECIFIER_QUALIFIER,
    STRUCT_DECLARATOR_LIST,
    STRUCT_DECLARATOR,
    DECLARATOR,
    POINTER,
    TYPE_QUALIFIER,







    // probably move this to the end of the file
    IDENTIFIER,




    DIRECT_DECLARATOR,

    CONSTANT_EXPRESSION,
    CONDITIONAL_EXPRESSION,
    LOGICAL_OR_EXPRESSION,
    LOGICAL_AND_EXPRESSION,
    INCLUSIVE_OR_EXPRESSION,
    EXCLUSIVE_OR_EXPRESSION,
    AND_EXPRESSION,
    EQUALITY_EXPRESSION,
    RELATIONAL_EXPRESSION,
    SHIFT_EXPRESSION,
    ADDITIVE_EXPRESSION,
    MULTIPLICATIVE_EXPRESSION,
    CAST_EXPRESSION,
    UNARY_EXPRESSION,
    POSTFIX_EXPRESSION,
    PRIMARY_EXPRESSION,

    CONSTANT,

    EXPRESSION,
    ASSIGNMENT_EXPRESSION,

    ASSIGNMENT_OPERATOR,
    UNARY_OPERATOR,

    COMPOUND_STATEMENT,
    STATEMENT,
    LABELED_STATEMENT,
    EXPRESSION_STATEMENT,
    SELECTION_STATEMENT,

    JUMP_STATEMENT,

}
