package com.monac.parser;

public enum NodeType {

    EQUALITY_EXPRESSION,
    RELATIONAL_EXPRESSION,
    SHIFT_EXPRESSION,
    ADDITIVE_EXPRESSION,
    MULTIPLICATIVE_EXPRESSION,
    CAST_EXPRESSION,
    UNARY_EXPRESSION,
    POSTFIX_EXPRESSION,
    PRIMARY_EXPRESSION,
    CONSTANT,

}
